### ISSUE TITLE
register_types.cpp:#include "core/object/class_db.h" does not exist in core.

### ISSUE THREAD

**Issue by invisiblesun** [godot-extended-libraries/godot-sqlite#15]
I followed your instructions to clone the sqlite repository and move it under modules. However the above include file leaked into godot core. I updated godot repo from master but this file is not in it.

**Comment by madmiraal** [comment]
This is the file on  godotengine/godot master:
https://github.com/godotengine/godot/blob/master/core/object/class_db.h

**Comment by invisiblesun** [comment]
Right, but I had been working from 3.2 branch. Without any indication that there was a branch dependency, I didn't know.

I am on a mac, and while 4.0 builds, it doesn't run because it can't find vulkan at the moment. After that I would have to contend with porting my godot project.

**Comment by madmiraal** [comment]
You can use the 3.2 branch of this module with the 3.2 branch of godot:
https://github.com/godot-extended-libraries/godot-sqlite/tree/3.2

**Comment by invisiblesun** [comment]
Thank you very much! I will look into it after I get reverted back to 3.2
