### ISSUE TITLE
SQLite methods need documentation

### ISSUE THREAD

**Issue by TGRCdev** [godot-extended-libraries/godot-sqlite#3]
There should be some form of documentation describing the actions and effects of each SQLite method. If possible, it should display in the editor as well.

**Comment by fire** [comment]
See editor documentation guide. 

https://godot.readthedocs.io/en/latest/community/contributing/updating_the_class_reference.html

**Comment by TGRCdev** [comment]
Editor documentation has been added with 9ac9058d3118cdadd40aa32c163c589e4980e3d8 and 7ef2816408d6dbaf52a9e97b48ef098ee12d0846.
