### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by TGRCdev** [godot-extended-libraries/godot-sqlite#4]
It would be nice to have a CI pipeline that makes sure any changes will build on all major Godot export platforms.

I'm well versed in Travis CI, but if anyone has a better service suggestion, feel free to discuss it.

We could also configure CI to output build artifacts like export templates and editor binaries, but this might be a bit tough to do. I have done it before for my [nightly gdsqlite-native builds](https://github.com/TGRCdev/gdsqlite-native/releases), though.

**Comment by fire** [comment]
I only have cicd code for some platforms. 

https://ifiregames.itch.io/stern-flowers-chibifire-com-godot-engine

If you want I can share my findings.

**Comment by fire** [comment]
@TGRCdev What's your discord? I'm in Godot discord.

**Comment by TGRCdev** [comment]
@fire [REMOVED]. We can continue talking on Discord.

**Comment by TGRCdev** [comment]
Accidentally hit close :/

**Comment by fire** [comment]
Ping!

**Comment by fire** [comment]
Completed.
